on:
  push:
    branches:
      - master
    tags:
      - "^[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_deploy:
      uses: sensirion/.github/.github/workflows/driver.python.pypi_publish.yml@main
      secrets:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

